CREATE DATABASE IF NOT EXISTS automotive_service_analytics;
USE automotive_service_analytics;
DROP TABLE IF EXISTS warranty_claims; DROP TABLE IF EXISTS invoices; DROP TABLE IF EXISTS work_order_parts; DROP TABLE IF EXISTS parts; DROP TABLE IF EXISTS work_orders; DROP TABLE IF EXISTS technicians; DROP TABLE IF EXISTS service_centers; DROP TABLE IF EXISTS vehicles; DROP TABLE IF EXISTS customers;

CREATE TABLE customers (customer_id INT PRIMARY KEY, customer_name VARCHAR(100) NOT NULL, city VARCHAR(50), state VARCHAR(50), region VARCHAR(20), customer_type ENUM('Individual','Fleet') NOT NULL, registration_date DATE);
CREATE TABLE vehicles (vehicle_id INT PRIMARY KEY, customer_id INT NOT NULL, vehicle_model VARCHAR(50) NOT NULL, vehicle_type VARCHAR(30), fuel_type VARCHAR(20), vehicle_year INT, purchase_date DATE, warranty_expiry_date DATE, current_mileage INT, FOREIGN KEY (customer_id) REFERENCES customers(customer_id));
CREATE TABLE service_centers (service_center_id INT PRIMARY KEY, service_center_name VARCHAR(100) NOT NULL, city VARCHAR(50), state VARCHAR(50), region VARCHAR(20), daily_capacity INT);
CREATE TABLE technicians (technician_id INT PRIMARY KEY, technician_name VARCHAR(100) NOT NULL, service_center_id INT NOT NULL, experience_years INT, specialization VARCHAR(50), FOREIGN KEY (service_center_id) REFERENCES service_centers(service_center_id));
CREATE TABLE parts (part_id INT PRIMARY KEY, part_name VARCHAR(100) NOT NULL, part_category VARCHAR(50), unit_cost DECIMAL(12,2), supplier VARCHAR(50));
CREATE TABLE work_orders (work_order_id INT PRIMARY KEY, vehicle_id INT NOT NULL, service_center_id INT NOT NULL, technician_id INT NOT NULL, open_date DATE NOT NULL, close_date DATE NULL, service_type VARCHAR(50), priority VARCHAR(20), status VARCHAR(20), odometer_reading INT, warranty_flag BOOLEAN, FOREIGN KEY(vehicle_id) REFERENCES vehicles(vehicle_id), FOREIGN KEY(service_center_id) REFERENCES service_centers(service_center_id), FOREIGN KEY(technician_id) REFERENCES technicians(technician_id));
CREATE TABLE work_order_parts (work_order_part_id INT PRIMARY KEY, work_order_id INT NOT NULL, part_id INT NOT NULL, quantity INT NOT NULL, unit_price DECIMAL(12,2) NOT NULL, FOREIGN KEY(work_order_id) REFERENCES work_orders(work_order_id), FOREIGN KEY(part_id) REFERENCES parts(part_id));
CREATE TABLE invoices (invoice_id INT PRIMARY KEY, work_order_id INT NOT NULL UNIQUE, invoice_date DATE NOT NULL, labor_cost DECIMAL(12,2), parts_cost DECIMAL(12,2), tax DECIMAL(12,2), discount DECIMAL(12,2), total_amount DECIMAL(12,2), payment_status VARCHAR(30), FOREIGN KEY(work_order_id) REFERENCES work_orders(work_order_id));
CREATE TABLE warranty_claims (claim_id INT PRIMARY KEY, work_order_id INT NOT NULL, claim_date DATE, failure_category VARCHAR(50), claim_amount DECIMAL(12,2), claim_status VARCHAR(30), approval_date DATE NULL, FOREIGN KEY(work_order_id) REFERENCES work_orders(work_order_id));
